{
  "id": "m016-1",
  "displayOrder": 62,
  "code": "m016",
  "variantNo": 1,
  "releaseDate": "2026-07-18",
  "releaseMonth": "2026-07",
  "name": "レザーポーチ入り インスタントティー Mystical Curiosities Ver.",
  "variant": "ST☆RISH",
  "price": 2200,
  "limit": 5,
  "category": "食品",
  "sales": "イベント・通販限定",
  "image": "https://www.utapri.com/grandshop/archive/2026/assets/img/goods/m016_rz3g/a01.jpg",
  "detail": "https://www.utapri.com/grandshop/item.php?id=m016",
  "random": false
},
{
  "id": "m016-2",
  "displayOrder": 62,
  "code": "m016",
  "variantNo": 2,
  "releaseDate": "2026-07-18",
  "releaseMonth": "2026-07",
  "name": "レザーポーチ入り インスタントティー Mystical Curiosities Ver.",
  "variant": "QUARTET NIGHT",
  "price": 2200,
  "limit": 5,
  "category": "食品",
  "sales": "イベント・通販限定",
  "image": "https://www.utapri.com/grandshop/archive/2026/assets/img/goods/m016_rz3g/b01.jpg",
  "detail": "https://www.utapri.com/grandshop/item.php?id=m016",
  "random": false
},
{
  "id": "m016-3",
  "displayOrder": 62,
  "code": "m016",
  "variantNo": 3,
  "releaseDate": "2026-07-18",
  "releaseMonth": "2026-07",
  "name": "レザーポーチ入り インスタントティー Mystical Curiosities Ver.",
  "variant": "HE★VENS",
  "price": 2200,
  "limit": 5,
  "category": "食品",
  "sales": "イベント・通販限定",
  "image": "https://www.utapri.com/grandshop/archive/2026/assets/img/goods/m016_rz3g/c01.jpg",
  "detail": "https://www.utapri.com/grandshop/item.php?id=m016",
  "random": false
},